services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    NOUT\Bundle\NOUTOnlineBundle\Service\:
        resource: '../../Service/*'
        #exclude: '../../{DependencyInjection,Entity,Migrations,Tests,NOUTOnlineBundle.php}'
        
    NOUT\Bundle\NOUTOnlineBundle\Service\NOUTClient:
        arguments:
            $sVersionMin:       '%noutonline.version_min%'
            $nVersionDialPref:  '%noutonline.version_dialogue_pref%'
            

    NOUT\Bundle\NOUTOnlineBundle\Service\ConnectionManager:
        arguments:
            $aAuth : '%nout_online.auth%'

    # pour la barre de debug
    NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineLogger:
        arguments:
            $debug: "%nout_online.log%"
        tags:
            - { name: monolog.logger, channel: noutonline }

    NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineDataCollector:
        tags:
            - { name: data_collector, template: "@NOUTOnline/DataCollector/layout.html.twig", id: "NOUTOnline" }

    NOUT\Bundle\NOUTOnlineBundle\Entity\ConfigurationDialogue:
        arguments:
            - '%nout_online.address%'
            - '%nout_online.port%'
            - '%nout_online.protocole%'
            - '%nout_online.apiuuid%'
            - '%version_site%'
            - '%noutweb.http_client%'
            - '%nout_online.auth%'
            - '%noutonline.version_dialogue_pref%'

    #factory pour les proxy
    NOUT\Bundle\NOUTOnlineBundle\Service\OnlineServiceFactory:
        arguments:
            $soap_socket_timeout: '%nout_online.soap_socket_timeout%'

    #factory pour les caches
    NOUT\Bundle\NOUTOnlineBundle\Cache\NOUTCacheFactory:
        arguments:
            $cachedir: "%kernel.cache_dir%"

    #les extension twigs
    NOUT\Bundle\NOUTOnlineBundle\Twig\NOUTOnlineExtension:
        arguments:
            $sVersionMin: '%noutonline.version_min%'
        tags:
            - { name: twig.extension }

    NOUT\Bundle\NOUTOnlineBundle\Twig\ToolsExtension:
        tags:
            - { name: twig.extension }
