parameters:
#    noutnout_online.example.class: NOUT\Bundle\NOUTOnlineBundle\Example

services:
#    noutnout_online.example:
#        class: %noutnout_online.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nout_contexts.client:
        class:      NOUT\Bundle\ContextsBundle\Service\NOUTClient
        arguments:
            - '@security.token_storage'
            - '@nout_online.service_factory'
            - '@nout_online.configuration_dialogue'
            - '@nout_online.cache_factory'
            - '%nout_online.version_min%'
            - '%nout_online.version_dialogue_pref%'
            - '@?debug.stopwatch'

    nout_contexts.record_serializer:
        class:  NOUT\Bundle\ContextsBundle\Service\RecordSerializer
        arguments:
            - '@security.token_storage'
            - '@nout_online.cache_factory'
    nout_online.connection_manager:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\ConnectionManager
        arguments:  ['%nout_online.auth%']

    # pour la barre de debug
    nout_online.logger:
        class:      NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineLogger
        arguments:  ['@logger', "%nout_online.log%"]
        tags:
            - { name: monolog.logger, channel: noutonline }

    nout_online.datacollector:
        class:      NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineDataCollector
        arguments:  ['@nout_online.logger', '@security.token_storage']
        tags:
            - { name: data_collector, template: "NOUTOnlineBundle:DataCollector:layout.html.twig", id: "NOUTOnline" }

    nout_online.client_information:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\ClientInformation
        arguments:  ["@request_stack"]

    nout_online.configuration_dialogue:
        class:      NOUT\Bundle\NOUTOnlineBundle\Entity\ConfigurationDialogue
        arguments:
            - '%nout_online.address%'
            - '%nout_online.port%'
            - '%nout_online.protocole%'
            - '%nout_online.apiuuid%'
            - '%version_site%'
            - '%nout.client%'
            - '%nout_online.auth%'
            - '%nout_online.version_dialogue_pref%'

    #factory pour les proxy
    nout_online.service_factory:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\OnlineServiceFactory
        arguments:
            - '@nout_online.client_information'
            - '@nout_online.logger'
            - '@nout_online.cache_factory'
            - '@?debug.stopwatch'
            - '%nout_online.soap_socket_timeout%'

    #factory pour les caches
    nout_online.cache_factory:
        class:      NOUT\Bundle\NOUTOnlineBundle\Cache\NOUTCacheFactory
        arguments:  ['@router', "%kernel.cache_dir%", '%kernel.project_dir%/config', '@?debug.stopwatch']

    #les extension twigs
    nout_online.twig.nout_online_extension:
        class:      NOUT\Bundle\NOUTOnlineBundle\Twig\NOUTOnlineExtension
        arguments:
            - '@nout_online.service_factory'
            - '@nout_online.configuration_dialogue'
            - '%nout_online.version_min%'
        tags:
            - { name: twig.extension }

    nout_online.twig.tools_extension:
        class:      NOUT\Bundle\NOUTOnlineBundle\Twig\ToolsExtension
        tags:
            - { name: twig.extension }
