parameters:
#    noutnout_online.example.class: NOUT\Bundle\NOUTOnlineBundle\Example

services:
#    noutnout_online.example:
#        class: %noutnout_online.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    nout_online.connection_manager:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\ConnectionManager
        arguments:  ['%nout_online.mode_auth%', '%secret%']

    # pour la barre de debug
    nout_online.logger:
        class:      NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineLogger
        arguments:  [@logger, "%nout_online.debug%"]
        tags:
            - { name: monolog.logger, channel: noutonline }

    nout_online.datacollector:
        class:      NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineDataCollector
        arguments:  [@nout_online.logger, @security.token_storage]
        tags:
            - { name: data_collector, template: "NOUTOnlineBundle:DataCollector:layout.html.twig", id: "NOUTOnline" }

    nout_online.cache:
        class:  NOUT\Bundle\NOUTOnlineBundle\Cache\NOUTCache
        arguments: ["%kernel.cache_dir%/soap"]

    nout_online.client_information:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\ClientInformation
        arguments:  ["@request_stack"]

    nout_online.configuration_dialogue:
        class:      NOUT\Bundle\NOUTOnlineBundle\Entity\ConfigurationDialogue
        arguments:
            - '%nout_online.address%'
            - '%nout_online.port%'
            - '%nout_online.protocole%'
            - '%nout_online.apiuuid%'
            - '%nout_web.version%'
            - '%nout_web.client% %societe%'
            - '%nout_online.mode_auth%'
            - '%secret%'

    #factory pour les proxy
    nout_online.service_factory:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\OnlineServiceFactory
        arguments:  [@nout_online.client_information, @nout_online.logger, @nout_online.cache]

    #les extension twigs
    nout_online.twig.nout_online_extension:
        class:      NOUT\Bundle\NOUTOnlineBundle\Twig\NOUTOnlineExtension
        arguments:
            - @nout_online.service_factory
            - @nout_online.configuration_dialogue
        tags:
            - { name: twig.extension }

    nout_online.twig.tools_extension:
        class:      NOUT\Bundle\NOUTOnlineBundle\Twig\ToolsExtension
        tags:
            - { name: twig.extension }


    #pour les forms de test
    nout_online.form.test_radio:
        class:      NOUT\Bundle\NOUTOnlineBundle\Form\Test\TestRadioType
        tags:
            - { name: form.type, alias: 'test_radio' }

    nout_online.form.test_radio_container:
        class:      NOUT\Bundle\NOUTOnlineBundle\Form\Test\TestRadioContainerType
        tags:
            - { name: form.type, alias: 'test_radio_container' }