parameters:
#    noutnout_online.example.class: NOUT\Bundle\NOUTOnlineBundle\Example

services:
#    noutnout_online.example:
#        class: %noutnout_online.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    nout_online.user_provider:
        class:      NOUT\Bundle\NOUTSessionManagerBundle\Security\Core\User\NOUTOnlineUserProvider
        arguments:  [@nout_online.service_factory, @nout_online.configuration_dialogue]

    nout_online.authentication_provider:
        class:      NOUT\Bundle\NOUTSessionManagerBundle\Security\Authentication\Provider\NOUTOnlineAuthenticationProvider
        arguments:
            - @nout_online.service_factory
            - @nout_online.configuration_dialogue
            - null #null remplacer par le replaceArgument du fichier \NOUT\Bundle\NOUTSessionManagerBundle\DependencyInjection\Factory\SecurityFactory.php
            - @security.user_checker
            - null #null remplacer par le replaceArgument du fichier \NOUT\Bundle\NOUTSessionManagerBundle\DependencyInjection\Factory\SecurityFactory.php
            - @security.encoder_factory
            - '%security.authentication.hide_user_not_found%'
