parameters:
#    nout_contextes.example.class: NOUTBundleContextsBundle\Example

services:
#    nout_contextes.example:
#        class: %nout_contextes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nout_contextes.client:
        class:      NOUTBundleContextsBundle\Service\NOUTClient
        arguments:  [@security.context, @nout_online.service_factory, @nout_online.configuration_dialogue, '%kernel.cache_dir%']
