parameters:
#    nout_contexts.example.class: NOUT\Bundle\ContextsBundle\Example

services:
#    nout_contexts.example:
#        class: %nout_contexts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nout_contexts.client:
        class:      NOUT\Bundle\ContextsBundle\Service\NOUTClient
        arguments:  [@security.token_storage, @nout_online.service_factory, @nout_online.configuration_dialogue, '%kernel.cache_dir%']

    nout_contexts.session_disconnect_listener:
        class:  NOUT\Bundle\ContextsBundle\Service\SessionDisconnectListener
        arguments: [@nout_contexts.client]
        tags:
          - { name: kernel.event_listener, event: session.disconnect, method: disconnect }
