parameters:
#    noutnout_online.example.class: NOUT\Bundle\NOUTOnlineBundle\Example

services:
    #http://blog.vandenbrand.org/2012/06/19/symfony2-authentication-provider-authenticate-against-webservice/
    nout_session.user_provider:
        class:      NOUT\Bundle\SessionManagerBundle\Security\Core\User\NOUTOnlineUserProvider
        arguments:  [@nout_online.service_factory, @nout_online.configuration_dialogue]

    nout_session.authentication_listener:
        class: NOUT\Bundle\SessionManagerBundle\Security\Firewall\NOUTOnlineListener
        arguments:
            - @security.context
            - @security.authentication.manager
            - @security.authentication.session_strategy
            - @security.http_utils
            - null
            - null
            - null
            - null
            - @logger
            - @event_dispatcher
        tags:
            - { name: 'monolog.logger', channel: 'security' }



    nout_session.authentication_provider:
        class:      NOUT\Bundle\SessionManagerBundle\Security\Authentication\Provider\NOUTOnlineAuthenticationProvider
        arguments:
            - @nout_online.service_factory
            - @nout_online.configuration_dialogue
            - null #null remplacer par le replaceArgument du fichier \NOUT\Bundle\SessionManagerBundle\DependencyInjection\Factory\SecurityFactory.php
            - @security.user_checker
            - null #null remplacer par le replaceArgument du fichier \NOUT\Bundle\SessionManagerBundle\DependencyInjection\Factory\SecurityFactory.php
            - @security.encoder_factory
            - '%security.authentication.hide_user_not_found%'
    nout_session.authentication_handler.logout_handler:
        class:      NOUT\Bundle\SessionManagerBundle\Security\Authentication\Handler\NOUTOnlineLogoutHandler
        arguments:  [@nout_online.service_factory, @nout_online.configuration_dialogue]
        tags:
            - { name: 'monolog.logger', channel: 'security' }


