parameters:
#    noutnout_online.example.class: NOUT\Bundle\NOUTOnlineBundle\Example

services:
#    noutnout_online.example:
#        class: %noutnout_online.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    nout_online.connection_manager:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\ConnectionManager
        arguments:  []

    # pour la barre de debug
    nout_online.logger:
        class:      NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineLogger
        arguments:  [@logger, "%nout_online.debug%"]
        tags:
            - { name: monolog.logger, channel: noutonline }

    nout_online.datacollector:
        class:      NOUT\Bundle\NOUTOnlineBundle\DataCollector\NOUTOnlineDataCollector
        arguments:  [@nout_online.logger, @security.context]
        tags:
            - { name: data_collector, template: "NOUTOnlineBundle:DataCollector:layout.html.twig", id: "NOUTOnline" }

    nout_online.cache:
        class:  NOUT\Bundle\NOUTOnlineBundle\Cache\NOUTCache
        arguments: ["%kernel.cache_dir%/soap"]

    nout_online.client_information:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\ClientInformation
        arguments:  ["@request_stack"]

    nout_online.configuration_dialogue:
        class:      NOUT\Bundle\NOUTOnlineBundle\Entity\ConfigurationDialogue
        arguments:  ['%nout_online.address%', '%nout_online.port%', '%nout_online.protocole%', '%nout_online.apiuuid%', '%noutweb_version%', '%noutweb_client% %societe%']

    #factory pour les proxy
    nout_online.service_factory:
        class:      NOUT\Bundle\NOUTOnlineBundle\Service\OnlineServiceFactory
        arguments:  [@nout_online.client_information, @nout_online.logger, @nout_online.cache]

    nout_online.twig.nout_online_extension:
        class:      NOUT\Bundle\NOUTOnlineBundle\Twig\NOUTOnlineExtension
        arguments:
            - @nout_online.service_factory
            - @nout_online.configuration_dialogue
        tags:
            - { name: twig.extension }

