<?php
/**
 * Created by PhpStorm.
 * User: Chris
 * Date: 12/12/2016
 * Time: 11:50
 */

namespace NOUT\Bundle\NOUTOnlineBundle\Entity\Parser;

/*
 * Parser pour le NOUVEAU planning (DHX)
 */

use NOUT\Bundle\NOUTOnlineBundle\Entity\Langage;
use NOUT\Bundle\NOUTOnlineBundle\Entity\Record\RecordList;
use NOUT\Bundle\NOUTOnlineBundle\Entity\Record\StructureElement;
use NOUT\Bundle\NOUTOnlineBundle\Entity\ReponseWebService\XMLResponseWS;

class ParserScheduler extends ParserList
{

    /** @var ParserXmlXsd */
    protected $m_clParserScheduler;


    public function __construct()
    {
        parent::__construct();
        $this->m_clParserScheduler = new ParserXmlXsd();
    }

    public function Parse(XMLResponseWS $clXMLReponseWS)
    {
        parent::Parse($clXMLReponseWS); // TODO: Change the autogenerated stub

        // Parser les utilisateurs
        $this->_ParseScheduler($clXMLReponseWS);
    }


    /**
     * Parse le scheduler
     * Ne doit pas etre trop volumineuse
     * @param XMLResponseWS $clReponseXML
     * @throws \Exception
     */
    protected function _ParseScheduler(XMLResponseWS $clReponseXML)
    {
        $ndSchema    = $clReponseXML->getNodeXSDRessource();
        $ndXML       = $clReponseXML->getNodeXMLRessource();
        $idForm      = Langage::TABL_Ressource; //toutes les ressources sont fils du tableau ressource

        if (count($ndSchema)>0)
        {
            $this->m_clParserScheduler->ParseXSD($ndSchema, StructureElement::NV_XSD_List);
        }

        if (count($ndXML)>0){
            $this->m_clParserScheduler->ParseXML($ndXML, $idForm, StructureElement::NV_XSD_List);
        }
    }

    /**
     * @return RecordList
     */
    public function getScheduler(): RecordList
    {
        $sIDForm        = Langage::TABL_Ressource;

        $clStructElem = $this->m_clParserList->getStructureElem($sIDForm, StructureElement::NV_XSD_List);


        $exports = $this->_getExports();
        $imports = $this->_getImports();

        // Instance d'une nouvelle clList avec toutes les donn�es pr�c�dentes
        $clList = new RecordList('', '', $sIDForm, $this->m_clParserScheduler->m_TabEnregTableau, $clStructElem, false, false, $exports, $imports);

        // Param�tres pour la clList
        $clList->setRecordCache($this->m_clParserScheduler->getFullCache());
        return $clList;
    }
}